name: Latest Dependency Checker
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'
    - name: Install pip and virtualenv
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
    - name: Update latest dependencies
      run: |
        python -m virtualenv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt
        make checkdeps OUTPUT_FILEPATH=utils/latest_dependencies.txt